import { PERMISSIONS, USER_ROLES, type Permission, type UserRole } from "@/lib/db";

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  "tenant.manage": "Manage school profile, configuration, and operational access.",
  "users.read": "View tenant users and role assignments.",
  "users.write": "Create and manage tenant memberships.",
  "academics.read": "View classes, sections, and enrollment structure.",
  "academics.write": "Create and manage classes, sections, and enrollments.",
  "academics.progression.read": "Preview academic progression and enrollment rollover.",
  "staff.read": "View staff directory and staffing records.",
  "staff.write": "Create and manage staff registry records.",
  "students.read": "View student records.",
  "students.write": "Create and update student records.",
  "students.create": "Create student records and initial enrollment.",
  "students.update": "Update student profiles and enrollment metadata.",
  "students.export": "Export authorized student directory data.",
  "students.import": "Validate and import student data files.",
  "students.archive": "Archive and reactivate student records.",
  "students.guardians.read": "View student guardian relationships.",
  "students.guardians.write": "Create and manage student guardian relationships.",
  "students.documents.read": "View student documents.",
  "students.documents.write": "Upload student documents.",
  "students.documents.verify": "Verify or reject student documents.",
  "students.notes.read": "View authorized internal student notes.",
  "students.notes.create": "Append internal student notes.",
  "students.notes.safeguarding": "View restricted safeguarding notes.",
  "attendance.read": "View attendance data and summaries.",
  "attendance.write": "Record and adjust attendance entries.",
  "fees.read": "View fee plans, invoices, and payment states.",
  "fees.write": "Manage fee plans, invoices, and receipts.",
  "announcements.read": "View notices and communication timelines.",
  "announcements.write": "Create and publish notices or announcements.",
  "reports.read": "View generated reports and academic summaries.",
  "admissions.read": "View admission enquiries and applications.",
  "admissions.write": "Manage admission enquiries and applications.",
  "curriculum.read": "View curriculum frameworks and subject offerings.",
  "curriculum.write": "Create and manage curriculum frameworks, offerings, and allocations.",
  "timetables.read": "View master, teacher, room, and class schedules.",
  "timetables.edit": "Create timetable versions and manage draft slots.",
  "timetables.settings.update": "Configure working days and timetable period definitions.",
  "learning.read": "View teaching and learning resources.",
  "assessments.read": "View assessments, marks, and results.",
  "assessments.plans.read": "View assessment plans and components.",
  "assessments.plans.write": "Create and manage assessment plans.",
  "assessments.schedule.read": "View exam schedules.",
  "assessments.schedule.write": "Create and manage exam events.",
  "assessments.marks.read": "View assessment marks.",
  "assessments.marks.write": "Enter and update assessment marks.",
  "assessments.marks.finalize": "Finalize assessment marks.",
  "assessments.results.read": "View computed assessment results.",
  "assessments.results.compute": "Compute assessment results.",
  "assessments.results.publish": "Publish assessment results.",
  "assessments.report-cards.read": "View report card generations.",
  "assessments.report-cards.manage": "Manage report card templates.",
  "assessments.report-cards.generate": "Generate report cards.",
  "hr.read": "View human-resources records and workflows.",
  "hr.staff.create": "Create staff records.",
  "hr.staff.update": "Update staff profile and employment records.",
  "hr.staff.export": "Export authorized staff directory data.",
  "hr.staff.import": "Validate and import staff data files.",
  "hr.staff.archive": "Archive and reactivate staff records.",
  "hr.departments.read": "View HR departments.",
  "hr.departments.create": "Create HR departments.",
  "hr.departments.update": "Update HR departments.",
  "hr.departments.archive": "Archive empty HR departments.",
  "hr.qualifications.manage": "Manage staff qualification records.",
  "payroll.read": "View payroll runs and statutory reports.",
  "payroll.settings.manage": "Manage payroll statutory and calendar settings.",
  "payroll.components.manage": "Manage payroll earnings and deduction components.",
  "payroll.assignments.manage": "Assign salary components to staff.",
  "payroll.runs.read": "View payroll runs and entries.",
  "payroll.runs.create": "Create payroll runs.",
  "payroll.runs.compute": "Compute and recompute payroll runs.",
  "payroll.runs.review": "Mark payroll runs reviewed.",
  "payroll.runs.lock": "Lock payroll runs and post payroll expenses.",
  "payroll.payslips.generate": "Generate payroll payslips.",
  "payroll.payslips.download": "Download payroll payslips.",
  "payroll.loans.manage": "Manage staff loans and advances.",
  "payroll.statutory.read": "View payroll statutory summaries.",
  "hr.contracts.read": "View staff contracts.",
  "hr.contracts.write": "Create and update staff contracts.",
  "hr.recruitment.read": "View recruitment pipeline records.",
  "hr.recruitment.write": "Manage recruitment pipeline records.",
  "hr.performance.read": "View performance review cycles.",
  "hr.performance.write": "Manage performance reviews.",
  "hr.leave.read": "View staff leave records.",
  "hr.leave.write": "Create and update staff leave requests.",
  "hr.leave.approve": "Approve or reject staff leave requests.",
  "approvals.read": "View actionable approval requests.",
  "finance.fees.read": "View fee plans, billing, and collections.",
  "finance.fees.write": "Create and manage fee structures, plans, and invoices.",
  "finance.fees.assign": "Assign fee plans and concessions to students.",
  "finance.fees.invoices.generate": "Generate student invoices from assigned fee plans.",
  "finance.fees.payments.record": "Record fee payments and issue receipts.",
  "finance.fees.void": "Void unpaid fee invoices.",
  "finance.accounting.read": "View accounting, budgets, and banking.",
  "finance.accounting.accounts.manage": "Manage chart of accounts.",
  "finance.accounting.expenses.record": "Record manual accounting expenses.",
  "transport.read": "View transport fleet, routes, and tracking.",
  "transport.fleet.write": "Create and update transport fleet records.",
  "transport.routes.manage": "Manage transport routes and stops.",
  "transport.allocations.manage": "Assign student transport routes and stops.",
  "transport.maintenance.manage": "Record vehicle maintenance and expenses.",
  "transport.tracking.read": "View transport GPS tracking events.",
  "library.read": "View the library catalog and circulation.",
  "library.settings.manage": "Manage library lending and fine settings.",
  "library.catalog.manage": "Manage library titles, copies, and accessions.",
  "library.members.manage": "Manage library members and borrowing limits.",
  "library.circulation.manage": "Issue, return, and renew library copies.",
  "library.fines.manage": "Manage library fine records.",
  "library.acquisitions.manage": "Manage library acquisitions and receiving.",
  "laboratories.read": "View laboratory bookings, stock, and safety.",
  "laboratories.manage": "Manage laboratory master records.",
  "laboratories.bookings.manage": "Create and manage laboratory bookings.",
  "laboratories.inventory.manage": "Manage laboratory equipment and consumables.",
  "laboratories.safety.manage": "Record and manage laboratory safety incidents.",
  "hostel.read": "View hostel buildings, rooms, and allocations.",
  "inventory.read": "View inventory, procurement, and assets.",
  "facilities.read": "View facilities, safety, and work orders.",
  "activities.read": "View activities, events, and achievements.",
  "communications.read": "View announcements and campaign delivery.",
  "documents.read": "View document templates, letters, and certificates.",
  "digital-experience.configure": "Configure portals, mobile apps, and branding.",
  "analytics.read": "View analytics dashboards and report catalogues.",
  "ai-studio.read": "Use approved AI Studio tools and copilots.",
  "administration.read": "View school administration settings.",
  "administration.users.read": "View users, roles, and access assignments.",
  "administration.users.create": "Invite and create school memberships.",
  "administration.users.update": "Update membership roles and status.",
  "administration.users.deactivate": "Deactivate and reactivate memberships.",
  "administration.users.reset": "Initiate password resets for memberships.",
  "administration.school.read": "View school profile and configuration.",
  "administration.school.update": "Update school profile and configuration.",
  "administration.roles.read": "View built-in and custom roles.",
  "administration.roles.create": "Create custom tenant roles.",
  "administration.roles.update": "Update custom roles and grants.",
  "administration.audit.read": "View tenant audit events.",
  "administration.integrations.read": "View tenant integration configuration.",
  "administration.integrations.update": "Configure active tenant integrations.",
};

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  superadmin: [...PERMISSIONS],
  admin: [...PERMISSIONS],
  teacher: [
    "academics.read",
    "staff.read",
    "students.read",
    "students.notes.read",
    "students.notes.create",
    "students.guardians.read",
    "attendance.read",
    "attendance.write",
    "announcements.read",
    "reports.read",
    "curriculum.read",
    "timetables.read",
    "learning.read",
    "assessments.read",
    "assessments.plans.read",
    "assessments.schedule.read",
    "assessments.marks.read",
    "assessments.marks.write",
    "assessments.results.read",
    "assessments.report-cards.read",
    "communications.read",
    "analytics.read",
    "ai-studio.read",
    "laboratories.read",
    "laboratories.bookings.manage",
  ],
  student: ["students.read", "announcements.read", "learning.read", "assessments.read", "finance.fees.read", "transport.read", "library.read", "communications.read"],
  parent: ["students.read", "students.guardians.read", "attendance.read", "fees.read", "announcements.read", "reports.read", "assessments.read", "finance.fees.read", "transport.read", "communications.read"],
  hr: [
    "staff.read",
    "staff.write",
    "hr.read",
    "hr.staff.create",
    "hr.staff.update",
    "hr.staff.export",
    "hr.staff.import",
    "hr.staff.archive",
    "hr.departments.read",
    "hr.departments.create",
    "hr.departments.update",
    "hr.departments.archive",
    "hr.qualifications.manage",
    "payroll.read",
    "payroll.settings.manage",
    "payroll.components.manage",
    "payroll.assignments.manage",
    "payroll.runs.read",
    "payroll.runs.create",
    "payroll.runs.compute",
    "payroll.payslips.generate",
    "payroll.payslips.download",
    "payroll.loans.manage",
    "payroll.statutory.read",
    "hr.contracts.read",
    "hr.contracts.write",
    "hr.recruitment.read",
    "hr.recruitment.write",
    "hr.performance.read",
    "hr.performance.write",
    "hr.leave.read",
    "hr.leave.write",
    "hr.leave.approve",
    "approvals.read",
  ],
  staff: ["academics.read", "staff.read", "students.read", "attendance.read", "announcements.read", "admissions.read", "curriculum.read", "timetables.read", "hr.read", "hr.leave.read", "hr.leave.write", "hr.performance.read", "payroll.payslips.download", "approvals.read", "transport.read", "laboratories.read", "laboratories.bookings.manage", "laboratories.inventory.manage", "laboratories.safety.manage", "communications.read"],
  accountant: ["academics.read", "staff.read", "students.read", "fees.read", "fees.write", "reports.read", "hr.read", "payroll.read", "payroll.runs.read", "payroll.runs.compute", "payroll.runs.review", "payroll.runs.lock", "payroll.payslips.generate", "payroll.payslips.download", "payroll.statutory.read", "approvals.read", "finance.fees.read", "finance.fees.write", "finance.fees.assign", "finance.fees.invoices.generate", "finance.fees.payments.record", "finance.fees.void", "finance.accounting.read", "finance.accounting.accounts.manage", "finance.accounting.expenses.record", "analytics.read"],
  librarian: ["students.read", "announcements.read", "library.read", "library.settings.manage", "library.catalog.manage", "library.members.manage", "library.circulation.manage", "library.fines.manage", "library.acquisitions.manage", "communications.read"],
};

export { PERMISSIONS, USER_ROLES };
