import { PERMISSIONS, USER_ROLES, type Permission, type UserRole } from "@/lib/db";

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  "tenant.manage": "Manage school profile, configuration, and operational access.",
  "users.read": "View tenant users and role assignments.",
  "users.write": "Create and manage tenant memberships.",
  "academics.read": "View classes, sections, and enrollment structure.",
  "academics.write": "Create and manage classes, sections, and enrollments.",
  "staff.read": "View staff directory and staffing records.",
  "staff.write": "Create and manage staff registry records.",
  "students.read": "View student records.",
  "students.write": "Create and update student records.",
  "attendance.read": "View attendance data and summaries.",
  "attendance.write": "Record and adjust attendance entries.",
  "fees.read": "View fee plans, invoices, and payment states.",
  "fees.write": "Manage fee plans, invoices, and receipts.",
  "announcements.read": "View notices and communication timelines.",
  "announcements.write": "Create and publish notices or announcements.",
  "reports.read": "View generated reports and academic summaries.",
  "admissions.read": "View admission enquiries and applications.",
  "admissions.write": "Manage admission enquiries and applications.",
  "curriculum.read": "View curriculum frameworks and subject offerings.",
  "timetables.read": "View master, teacher, room, and class schedules.",
  "learning.read": "View teaching and learning resources.",
  "assessments.read": "View assessments, marks, and results.",
  "hr.read": "View human-resources records and workflows.",
  "payroll.read": "View payroll runs and statutory reports.",
  "finance.fees.read": "View fee plans, billing, and collections.",
  "finance.accounting.read": "View accounting, budgets, and banking.",
  "transport.read": "View transport fleet, routes, and tracking.",
  "library.read": "View the library catalog and circulation.",
  "laboratories.read": "View laboratory bookings, stock, and safety.",
  "hostel.read": "View hostel buildings, rooms, and allocations.",
  "inventory.read": "View inventory, procurement, and assets.",
  "facilities.read": "View facilities, safety, and work orders.",
  "activities.read": "View activities, events, and achievements.",
  "communications.read": "View announcements and campaign delivery.",
  "documents.read": "View document templates, letters, and certificates.",
  "digital-experience.configure": "Configure portals, mobile apps, and branding.",
  "analytics.read": "View analytics dashboards and report catalogues.",
  "ai-studio.read": "Use approved AI Studio tools and copilots.",
  "administration.read": "View school administration settings.",
  "administration.users.read": "View users, roles, and access assignments.",
  "administration.audit.read": "View tenant audit events.",
};

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  superadmin: [...PERMISSIONS],
  admin: [...PERMISSIONS],
  teacher: [
    "academics.read",
    "staff.read",
    "students.read",
    "attendance.read",
    "attendance.write",
    "announcements.read",
    "reports.read",
    "curriculum.read",
    "timetables.read",
    "learning.read",
    "assessments.read",
    "communications.read",
    "analytics.read",
    "ai-studio.read",
  ],
  student: ["announcements.read", "learning.read", "assessments.read", "communications.read"],
  parent: ["attendance.read", "fees.read", "announcements.read", "reports.read", "assessments.read", "finance.fees.read", "communications.read"],
  staff: ["academics.read", "staff.read", "students.read", "attendance.read", "announcements.read", "admissions.read", "curriculum.read", "timetables.read", "hr.read", "communications.read"],
  accountant: ["academics.read", "staff.read", "students.read", "fees.read", "fees.write", "reports.read", "hr.read", "payroll.read", "finance.fees.read", "finance.accounting.read", "analytics.read"],
  librarian: ["students.read", "announcements.read", "library.read", "communications.read"],
};

export { PERMISSIONS, USER_ROLES };
