/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CmsRouteImport } from './routes/cms'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as IndexRouteImport } from './routes/index'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CmsRoute = CmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/ai-studio': typeof AiStudioRoute
  '/attendance': typeof AttendanceRoute
  '/cms': typeof CmsRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/intelligence': typeof IntelligenceRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/mobile': typeof MobileRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/ai-studio': typeof AiStudioRoute
  '/attendance': typeof AttendanceRoute
  '/cms': typeof CmsRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/intelligence': typeof IntelligenceRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/mobile': typeof MobileRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/ai-studio': typeof AiStudioRoute
  '/attendance': typeof AttendanceRoute
  '/cms': typeof CmsRoute
  '/communications': typeof CommunicationsRoute
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/fees': typeof FeesRoute
  '/intelligence': typeof IntelligenceRoute
  '/labs': typeof LabsRoute
  '/library': typeof LibraryRoute
  '/mobile': typeof MobileRoute
  '/payroll': typeof PayrollRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/students': typeof StudentsRoute
  '/timetable': typeof TimetableRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/ai-studio'
    | '/attendance'
    | '/cms'
    | '/communications'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/intelligence'
    | '/labs'
    | '/library'
    | '/mobile'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/ai-studio'
    | '/attendance'
    | '/cms'
    | '/communications'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/intelligence'
    | '/labs'
    | '/library'
    | '/mobile'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/ai-studio'
    | '/attendance'
    | '/cms'
    | '/communications'
    | '/dashboard'
    | '/exams'
    | '/fees'
    | '/intelligence'
    | '/labs'
    | '/library'
    | '/mobile'
    | '/payroll'
    | '/settings'
    | '/staff'
    | '/students'
    | '/timetable'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicsRoute: typeof AcademicsRoute
  AdminRoute: typeof AdminRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AiStudioRoute: typeof AiStudioRoute
  AttendanceRoute: typeof AttendanceRoute
  CmsRoute: typeof CmsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  FeesRoute: typeof FeesRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LabsRoute: typeof LabsRoute
  LibraryRoute: typeof LibraryRoute
  MobileRoute: typeof MobileRoute
  PayrollRoute: typeof PayrollRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StudentsRoute: typeof StudentsRoute
  TimetableRoute: typeof TimetableRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cms': {
      id: '/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof CmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicsRoute: AcademicsRoute,
  AdminRoute: AdminRoute,
  AdmissionsRoute: AdmissionsRoute,
  AiStudioRoute: AiStudioRoute,
  AttendanceRoute: AttendanceRoute,
  CmsRoute: CmsRoute,
  CommunicationsRoute: CommunicationsRoute,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  FeesRoute: FeesRoute,
  IntelligenceRoute: IntelligenceRoute,
  LabsRoute: LabsRoute,
  LibraryRoute: LibraryRoute,
  MobileRoute: MobileRoute,
  PayrollRoute: PayrollRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StudentsRoute: StudentsRoute,
  TimetableRoute: TimetableRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
