import "server-only";

import { and, desc, eq } from "drizzle-orm";
import { ai } from "@/lib/ai/client";
import { aiGenerations, aiKnowledgeBase, aiSettings, auditLogs, reportCardGenerations } from "@/lib/db";
import { withTenant } from "@/lib/rls";
import { Phase12Error } from "./analytics";

export const AI_FEATURES = [
  { key: "exam_generator", label: "Exam Generator", description: "Draft question papers and answer keys from curriculum context." },
  { key: "lesson_planner", label: "Lesson Planner", description: "Create lesson objectives, activities, assessments, and homework." },
  { key: "report_card_comments", label: "Report Card Comments", description: "Draft reviewed narrative comments for report cards." },
  { key: "communication_writer", label: "Communication Writer", description: "Draft announcements, SMS, email, and push copy." },
] as const;

export type AIFeatureKey = (typeof AI_FEATURES)[number]["key"];

export const AI_KNOWLEDGE_CATEGORIES = ["school_info", "curriculum", "policies", "exam_pattern", "other"] as const;

const DEFAULT_MONTHLY_TOKEN_LIMIT = 500000;
const MODEL_NAME = "gemini-2.5-flash";

function defaultFeatures() {
  return AI_FEATURES.map((feature) => feature.key);
}

function estimateTokens(text: string) {
  return Math.max(1, Math.ceil(text.length / 4));
}

function summarize(input: Record<string, unknown>) {
  const topic = typeof input.topic === "string" ? input.topic : typeof input.subject === "string" ? input.subject : "AI Studio request";
  return String(topic).slice(0, 500);
}

function fallbackOutput(feature: AIFeatureKey, prompt: string) {
  const title = AI_FEATURES.find((item) => item.key === feature)?.label ?? "AI Draft";
  return [
    `${title} Draft`,
    "",
    "This draft was generated by the local safe fallback because the hosted AI key is not configured or the provider call failed.",
    "",
    "Request context:",
    prompt.slice(0, 1800),
    "",
    "Review checklist:",
    "- Confirm factual accuracy and school policy alignment.",
    "- Edit tone, names, dates, and marks before applying.",
    "- Keep the final content under human approval.",
  ].join("\n");
}

export async function ensureAISettings(tenantId: string) {
  return withTenant(tenantId, async (tx) => {
    const [existing] = await tx.select().from(aiSettings).where(eq(aiSettings.tenantId, tenantId)).limit(1);
    if (existing) return existing;
    const [created] = await tx.insert(aiSettings).values({
      tenantId,
      featuresEnabled: defaultFeatures(),
      monthlyTokenLimit: DEFAULT_MONTHLY_TOKEN_LIMIT,
      tokensUsedThisMonth: 0,
      usageResetDate: new Date().toISOString().slice(0, 10),
    }).returning();
    return created;
  });
}

async function generateProviderText(prompt: string) {
  if (!ai) return fallbackOutput("lesson_planner", prompt);
  try {
    const response = await ai.models.generateContent({ model: MODEL_NAME, contents: prompt });
    return response.text || fallbackOutput("lesson_planner", prompt);
  } catch {
    return fallbackOutput("lesson_planner", prompt);
  }
}

export async function generateAIContent(tenantId: string, userId: string, input: { feature: AIFeatureKey; prompt?: string; context?: Record<string, unknown> }) {
  const feature = AI_FEATURES.find((item) => item.key === input.feature);
  if (!feature) throw new Phase12Error("Unknown AI Studio feature.", 404);

  return withTenant(tenantId, async (tx) => {
    let [settings] = await tx.select().from(aiSettings).where(eq(aiSettings.tenantId, tenantId)).limit(1);
    if (!settings) {
      [settings] = await tx.insert(aiSettings).values({
        tenantId,
        featuresEnabled: defaultFeatures(),
        monthlyTokenLimit: DEFAULT_MONTHLY_TOKEN_LIMIT,
        tokensUsedThisMonth: 0,
        usageResetDate: new Date().toISOString().slice(0, 10),
      }).returning();
    }

    const enabled = settings.featuresEnabled?.length ? settings.featuresEnabled : defaultFeatures();
    if (!enabled.includes(input.feature)) throw new Phase12Error("This AI Studio feature is disabled for the tenant.", 403);

    const knowledge = await tx
      .select({ title: aiKnowledgeBase.title, content: aiKnowledgeBase.content, category: aiKnowledgeBase.category })
      .from(aiKnowledgeBase)
      .where(and(eq(aiKnowledgeBase.tenantId, tenantId), eq(aiKnowledgeBase.isActive, true)))
      .limit(8);

    const context = input.context ?? {};
    const prompt = [
      `You are assisting a school ERP user with: ${feature.label}.`,
      "Create a useful draft only. Do not claim it is final; it requires human review before use.",
      "",
      "Tenant knowledge base:",
      ...knowledge.map((doc) => `- ${doc.title} [${doc.category}]: ${doc.content.slice(0, 900)}`),
      "",
      "User request:",
      input.prompt ?? "",
      "",
      "Structured context:",
      JSON.stringify(context).slice(0, 2500),
    ].join("\n");

    const promptTokens = estimateTokens(prompt);
    if (settings.tokensUsedThisMonth + promptTokens > settings.monthlyTokenLimit) {
      throw new Phase12Error("Monthly AI token limit exceeded.", 429);
    }

    const output = await generateProviderText(prompt);
    const outputTokens = estimateTokens(output);
    const [generation] = await tx.insert(aiGenerations).values({
      tenantId,
      feature: input.feature,
      model: MODEL_NAME,
      promptTokens,
      outputTokens,
      inputSummary: summarize({ ...context, topic: input.prompt }),
      output,
      status: "draft",
      createdBy: userId,
    }).returning();

    await tx.update(aiSettings).set({
      tokensUsedThisMonth: settings.tokensUsedThisMonth + promptTokens + outputTokens,
      updatedAt: new Date(),
    }).where(eq(aiSettings.tenantId, tenantId));

    return generation;
  });
}

export async function listAIGenerations(tenantId: string, feature?: string | null) {
  return withTenant(tenantId, (tx) => tx
    .select()
    .from(aiGenerations)
    .where(feature ? and(eq(aiGenerations.tenantId, tenantId), eq(aiGenerations.feature, feature)) : eq(aiGenerations.tenantId, tenantId))
    .orderBy(desc(aiGenerations.createdAt))
    .limit(50));
}

export async function reviewAIGeneration(tenantId: string, userId: string, id: string, status: "reviewed" | "rejected" | "archived") {
  return withTenant(tenantId, async (tx) => {
    const [updated] = await tx.update(aiGenerations).set({ status, reviewedBy: userId, reviewedAt: new Date() }).where(and(eq(aiGenerations.tenantId, tenantId), eq(aiGenerations.id, id))).returning();
    if (!updated) throw new Phase12Error("AI generation not found.", 404);
    await tx.insert(auditLogs).values({ tenantId, actorUserId: userId, action: `ai.${status}`, entityType: "ai_generation", entityId: id, metadata: { feature: updated.feature } });
    return updated;
  });
}

export async function applyAIGeneration(tenantId: string, userId: string, id: string, input: { appliedToType?: string | null; appliedToId?: string | null; editedOutput?: string | null }) {
  return withTenant(tenantId, async (tx) => {
    const [generation] = await tx.select().from(aiGenerations).where(and(eq(aiGenerations.tenantId, tenantId), eq(aiGenerations.id, id))).limit(1);
    if (!generation) throw new Phase12Error("AI generation not found.", 404);
    if (!["draft", "reviewed"].includes(generation.status)) throw new Phase12Error("Only draft or reviewed AI outputs can be applied.", 409);

    const output = input.editedOutput?.trim() || generation.output;
    if (generation.feature === "report_card_comments" && input.appliedToId) {
      await tx.update(reportCardGenerations).set({ customComment: output, updatedAt: new Date() }).where(and(eq(reportCardGenerations.tenantId, tenantId), eq(reportCardGenerations.id, input.appliedToId)));
    }

    const [updated] = await tx.update(aiGenerations).set({
      output,
      status: "applied",
      reviewedBy: userId,
      reviewedAt: new Date(),
      appliedToType: input.appliedToType ?? null,
      appliedToId: input.appliedToId ?? null,
    }).where(and(eq(aiGenerations.tenantId, tenantId), eq(aiGenerations.id, id))).returning();

    await tx.insert(auditLogs).values({ tenantId, actorUserId: userId, action: "ai.applied", entityType: "ai_generation", entityId: id, metadata: { feature: updated.feature, appliedToType: updated.appliedToType, appliedToId: updated.appliedToId } });
    return updated;
  });
}

export async function listAIKnowledgeBase(tenantId: string) {
  return withTenant(tenantId, (tx) => tx.select().from(aiKnowledgeBase).where(eq(aiKnowledgeBase.tenantId, tenantId)).orderBy(desc(aiKnowledgeBase.createdAt)).limit(100));
}

export async function createAIKnowledgeBaseDoc(tenantId: string, userId: string, input: { title: string; content: string; category?: string; isActive?: boolean }) {
  if (!input.title.trim() || !input.content.trim()) throw new Phase12Error("Knowledge base title and content are required.", 422);
  const category = AI_KNOWLEDGE_CATEGORIES.includes(input.category as (typeof AI_KNOWLEDGE_CATEGORIES)[number]) ? input.category : "other";
  return withTenant(tenantId, async (tx) => {
    const [doc] = await tx.insert(aiKnowledgeBase).values({ tenantId, title: input.title.trim(), content: input.content.trim(), category, isActive: input.isActive ?? true, createdBy: userId }).returning();
    return doc;
  });
}

export async function updateAISettings(tenantId: string, input: { featuresEnabled?: string[]; monthlyTokenLimit?: number; resetUsage?: boolean }) {
  const enabled = input.featuresEnabled?.filter((feature): feature is AIFeatureKey => AI_FEATURES.some((item) => item.key === feature));
  return withTenant(tenantId, async (tx) => {
    const [existing] = await tx.select().from(aiSettings).where(eq(aiSettings.tenantId, tenantId)).limit(1);
    const values = {
      featuresEnabled: enabled ?? existing?.featuresEnabled ?? defaultFeatures(),
      monthlyTokenLimit: input.monthlyTokenLimit ?? existing?.monthlyTokenLimit ?? DEFAULT_MONTHLY_TOKEN_LIMIT,
      tokensUsedThisMonth: input.resetUsage ? 0 : existing?.tokensUsedThisMonth ?? 0,
      usageResetDate: input.resetUsage ? new Date().toISOString().slice(0, 10) : existing?.usageResetDate ?? new Date().toISOString().slice(0, 10),
      updatedAt: new Date(),
    };
    if (!existing) {
      const [created] = await tx.insert(aiSettings).values({ tenantId, ...values }).returning();
      return created;
    }
    const [updated] = await tx.update(aiSettings).set(values).where(eq(aiSettings.tenantId, tenantId)).returning();
    return updated;
  });
}
