-- ATTENDANCE LOGS PARTITIONING
-- Strategy: PARTITION BY RANGE (timestamp)
-- Drop the standard table if auto-generated by ORM and recreate as partitioned
DROP TABLE IF EXISTS attendance_logs;

CREATE TABLE attendance_logs (
    id UUID DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    student_id UUID NOT NULL REFERENCES students(id),
    timestamp TIMESTAMP NOT NULL,
    source text NOT NULL CHECK (source IN ('manual', 'biometric')),
    marked_by UUID,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP,
    -- Partition Key must be included in the primary definition if we enforced PKEY
    PRIMARY KEY (id, timestamp) 
) PARTITION BY RANGE (timestamp);

-- Create initial partitions (Example: Current Year)
-- Monthly granularity recommended
CREATE TABLE attendance_logs_2025_01 PARTITION OF attendance_logs
    FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');

CREATE TABLE attendance_logs_2025_02 PARTITION OF attendance_logs
    FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');

-- ENABLE RLS
ALTER TABLE devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;

-- DEVICES POLICY (Admin Access)
CREATE POLICY tenant_isolation_devices ON devices
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- ATTENDANCE POLICY
-- Standard isolation
CREATE POLICY tenant_isolation_attendance ON attendance_logs
    USING (tenant_id = current_setting('app.current_tenant')::uuid)
    WITH CHECK (tenant_id = current_setting('app.current_tenant')::uuid);

-- FORCE RLS
ALTER TABLE devices FORCE ROW LEVEL SECURITY;
ALTER TABLE attendance_logs FORCE ROW LEVEL SECURITY;