import type { ReactNode } from "react";
import {
  LayoutDashboard,
  ClipboardCheck,
  CalendarDays,
  BookOpenCheck,
  Users,
  GraduationCap,
  UserCog,
  Wallet,
  Bus,
  MessageSquare,
  Sparkles,
  ShieldCheck,
  Settings,
  Banknote,
  Library,
  FlaskConical,
  Smartphone,
  School,
} from "lucide-react";

export type SubFlow = { id: string; label: string; count?: number };
export type ModuleEntry = {
  key: string;
  title: string;
  url: string;
  icon: ReactNode;
  flows?: SubFlow[]; // sub-flows shown in sidebar accordion; navigate via ?tab=<id>
};

export type ModuleGroup = { label: string; modules: ModuleEntry[] };

// Master navigation for the tenant workspace. Sub-flows are flattened here so
// the main sidebar exposes them directly (no secondary rail).
export const NAV: ModuleGroup[] = [
  {
    label: "Overview",
    modules: [{ key: "dashboard", title: "Dashboard", url: "/dashboard", icon: <LayoutDashboard className="h-4 w-4" /> }],
  },
  {
    label: "Academics",
    modules: [
      {
        key: "academics",
        title: "Academics Setup",
        url: "/academics",
        icon: <School className="h-4 w-4" />,
        flows: [
          { id: "overview", label: "Overview" },
          { id: "classes", label: "Classes & Sections" },
          { id: "subjects", label: "Subjects" },
          { id: "mapping", label: "Class × Subject" },
          { id: "streams", label: "Streams & Electives" },
          { id: "houses", label: "House System" },
          { id: "calendar", label: "Academic Calendar" },
          { id: "roster", label: "Section Roster" },
          { id: "load", label: "Teaching Load" },
          { id: "coverage", label: "Curriculum Coverage" },
          { id: "grading", label: "Grading Scheme" },
          { id: "session", label: "Session / Rollover" },
          { id: "naming", label: "Naming Templates" },
          { id: "board", label: "Curriculum Board" },
        ],
      },
      {
        key: "attendance",
        title: "Attendance",
        url: "/attendance",
        icon: <ClipboardCheck className="h-4 w-4" />,
        flows: [
          { id: "feed", label: "Feed Attendance" },
          { id: "feed-monthly", label: "Monthly Feed" },
          { id: "sms", label: "SMS Absentees" },
          { id: "leave", label: "Leave Applications", count: 3 },
          { id: "monthly-class", label: "Monthly · Class" },
          { id: "annual-pct", label: "Annual %" },
          { id: "perfect", label: "100% Attendance" },
          { id: "cfg-holidays", label: "Holidays" },
        ],
      },
      { key: "timetable", title: "Timetable", url: "/timetable", icon: <CalendarDays className="h-4 w-4" /> },
      {
        key: "exams",
        title: "Exams",
        url: "/exams",
        icon: <BookOpenCheck className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "feed-marks", label: "Feed Marks" },
          { id: "marks-entry", label: "Marks Entry" },
          { id: "class-marksheet", label: "Class Marksheet" },
          { id: "student-marksheet", label: "Student Marksheet" },
          { id: "toppers", label: "Toppers" },
          { id: "hall-ticket", label: "Hall Tickets" },
          { id: "cfg-structure", label: "Exam Structure" },
          { id: "cfg-grades", label: "Grade Slabs" },
        ],
      },
    ],
  },
  {
    label: "People",
    modules: [
      {
        key: "students",
        title: "Students",
        url: "/students",
        icon: <Users className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "list", label: "All Students" },
          { id: "add", label: "Add Student" },
          { id: "import", label: "Bulk Import" },
          { id: "promote", label: "Promote / Detain" },
          { id: "siblings", label: "Siblings" },
          { id: "birthdays", label: "Birthdays" },
          { id: "id-card", label: "ID Cards" },
        ],
      },
      { key: "admissions", title: "Admissions", url: "/admissions", icon: <GraduationCap className="h-4 w-4" /> },
      {
        key: "staff",
        title: "Staff",
        url: "/staff",
        icon: <UserCog className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "list", label: "All Staff" },
          { id: "departments", label: "Departments" },
          { id: "add", label: "Add Staff" },
          { id: "notes", label: "Notes" },
          { id: "id-card", label: "ID Cards" },
          { id: "birthdays", label: "Birthdays" },
        ],
      },
      {
        key: "payroll",
        title: "Payroll",
        url: "/payroll",
        icon: <Banknote className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "run", label: "Run Payroll" },
          { id: "slips", label: "Salary Slips" },
          { id: "bonus", label: "Bonuses & Deductions" },
          { id: "advances", label: "Advances & Loans" },
          { id: "reimbursements", label: "Reimbursements" },
          { id: "approvals", label: "Approvals Queue", count: 4 },
          { id: "bank-file", label: "Bank File Export" },
          { id: "register", label: "Payroll Register" },
          { id: "tds", label: "TDS Statement" },
          { id: "statutory", label: "PF / ESI / PT" },
          { id: "structures", label: "Salary Structures" },
          { id: "components", label: "Components" },
          { id: "grades", label: "Salary Grades" },
        ],
      },
    ],
  },
  {
    label: "Operations",
    modules: [
      { key: "fees", title: "Fees", url: "/fees", icon: <Wallet className="h-4 w-4" /> },
      { key: "vehicles", title: "Vehicles", url: "/vehicles", icon: <Bus className="h-4 w-4" /> },
      { key: "communications", title: "Communications", url: "/communications", icon: <MessageSquare className="h-4 w-4" /> },
    ],
  },
  {
    label: "Facilities",
    modules: [
      {
        key: "library",
        title: "Library",
        url: "/library",
        icon: <Library className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "issue", label: "Issue Book" },
          { id: "return", label: "Return Book" },
          { id: "reserve", label: "Reservations" },
          { id: "fines", label: "Fines" },
          { id: "lost", label: "Lost / Damaged" },
          { id: "catalog", label: "Catalog" },
          { id: "members", label: "Members" },
          { id: "overdue", label: "Overdue", count: 18 },
          { id: "reports", label: "Circulation" },
          { id: "cfg-rules", label: "Membership Rules" },
          { id: "cfg-fines", label: "Fine Slabs" },
        ],
      },
      {
        key: "labs",
        title: "Labs",
        url: "/labs",
        icon: <FlaskConical className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Dashboard" },
          { id: "booking", label: "Lab Booking" },
          { id: "sessions", label: "Session Log" },
          { id: "equipment", label: "Equipment" },
          { id: "consumables", label: "Consumables" },
          { id: "chemicals", label: "Chemicals" },
          { id: "incidents", label: "Incidents" },
          { id: "safety", label: "Safety Checklists" },
          { id: "vendors", label: "Vendors" },
          { id: "po", label: "Purchase Orders" },
          { id: "cfg-labs", label: "Lab Master" },
        ],
      },
    ],
  },
  {
    label: "AI Studio",
    modules: [
      {
        key: "ai-studio",
        title: "AI Studio",
        url: "/ai-studio",
        icon: <Sparkles className="h-4 w-4" />,
        flows: [
          { id: "overview", label: "Overview" },
          { id: "notice", label: "Notice Composer" },
          { id: "syllabus", label: "Syllabus Drafter" },
          { id: "exam-creator", label: "Exam / Test Creator" },
          { id: "question-bank", label: "Question Bank" },
          { id: "worksheet", label: "Worksheet & Homework" },
          { id: "comments", label: "Report Card Comments" },
          { id: "lesson", label: "Lesson Plan" },
          { id: "circular", label: "Circular & Newsletter" },
          { id: "certificate", label: "Certificate Generator" },
          { id: "timetable-ai", label: "Timetable Suggester" },
          { id: "interview", label: "Admissions Interview Qs" },
          { id: "teacher-copilot", label: "Teacher Copilot" },
          { id: "principal-copilot", label: "Principal Copilot" },
          { id: "parent-copilot", label: "Parent Copilot" },
          { id: "monitors", label: "Monitors / Insights" },
          { id: "kb", label: "Knowledge Base" },
          { id: "prompts", label: "Prompts & Templates" },
          { id: "governance", label: "Usage & Governance" },
        ],
      },
      { key: "intelligence", title: "Legacy Insights", url: "/intelligence", icon: <Sparkles className="h-4 w-4" /> },
    ],
  },
  {
    label: "Mobile",
    modules: [
      {
        key: "mobile",
        title: "App Management",
        url: "/mobile",
        icon: <Smartphone className="h-4 w-4" />,
        flows: [
          { id: "dashboard", label: "Adoption" },
          { id: "parents", label: "Parents & Students" },
          { id: "teachers", label: "Teachers" },
          { id: "devices", label: "Devices" },
          { id: "homework", label: "Homework Publisher" },
          { id: "visibility", label: "Exam Visibility" },
          { id: "push", label: "Notification Center" },
          { id: "fees-visibility", label: "Fees Visibility" },
          { id: "announcements", label: "Announcements" },
          { id: "flags", label: "Feature Flags" },
          { id: "branding", label: "App Branding" },
          { id: "version", label: "App Version" },
          { id: "support", label: "Support Tickets", count: 6 },
        ],
      },
    ],
  },
  {
    label: "Admin",
    modules: [
      { key: "admin", title: "App Admin (RBAC)", url: "/admin", icon: <ShieldCheck className="h-4 w-4" /> },
      { key: "settings", title: "Settings", url: "/settings", icon: <Settings className="h-4 w-4" /> },
    ],
  },
];
